
trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image and Push Docker Image
  jobs:
  - job: Build
    displayName: Build and Push Docker Image
    pool:
      vmImage: ubuntu-latest
    steps:
        - task: Docker@2
          inputs:
           containerRegistry: docker
           repository: azuredevopsguru/app1
           command: 'buildAndPush'
           Dockerfile: '$(Build.SourcesDirectory)/Dockerfile' 
           tags: 'latest' 
  




    

    


